### ISSUE TITLE
Popen is not Sendable on Windows

### ISSUE THREAD

**Issue by zonyitoo** [hniksic/rust-subprocess#14]
I got this error on Windows:

```
error[E0277]: the trait bound `*mut std::os::raw::c_void: std::marker::Send` is not satisfied in `plugin::Plugin`
  --> src\monitor.rs:80:48
   |
80 | pub fn monitor_signal(plugins: Vec<Plugin>) -> impl Future<Item = (), Error = io::Error> + Send {
   |                                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ `*mut std::os::raw::c_void` cannot be sent between threads safely
   |
   = help: within `plugin::Plugin`, the trait `std::marker::Send` is not implemented for `*mut std::os::raw::c_void`
   = note: required because it appears within the type `subprocess::win32::Handle`
   = note: required because it appears within the type `subprocess::popen::os::ExtChildState`
   = note: required because it appears within the type `subprocess::popen::ChildState`
   = note: required because it appears within the type `subprocess::Popen`
   = note: required because it appears within the type `plugin::Plugin`
   = note: required because of the requirements on the impl of `std::marker::Send` for `std::ptr::Unique<plugin::Plugin>`
   = note: required because it appears within the type `alloc::raw_vec::RawVec<plugin::Plugin>`
   = note: required because it appears within the type `std::vec::Vec<plugin::Plugin>`
```

I have a struct `Plugin` with a member of type `subprocess::Popen`.

Can `Popen` be `Send`?

**Comment by hniksic** [comment]
Yes, definitely - it not being `Send` is accidental, due to use of `win32::Handle` in `ExtChildState`.

The way `ExtChildState` is used is definitely `Send`-safe, so `ExtChildState` just misses the appropriate `unsafe impl`. Or the `unsafe impl` could be in `win32` where the unsafe code is kept - the standard library routinely implements `Send` for [all its handles](https://github.com/rust-lang/rust/blob/2612bbcba08dd81730edd8f2139005fb7a409294/src/libstd/sys/windows/handle.rs#L35).

**Comment by zonyitoo** [comment]
Maybe you could `unsafe impl Send` for `ExtChildStat`?

**Comment by hniksic** [comment]
I've now added a `Send` implementation for `win32::Handle`, which should automatically extend to `ExtChildState`. @zonyitoo Can you check if it works for you in 0.1.13?

**Comment by zonyitoo** [comment]
Yes, it works well.

**Comment by zonyitoo** [comment]
Closing this issue. Can you publish 0.1.13?

**Comment by hniksic** [comment]
Sure, it was published yesterday. Thanks for the report.

**Comment by zonyitoo** [comment]
Thanks.

**Comment by zonyitoo** [comment]
Is it really published? https://crates.io/crates/subprocess

**Comment by hniksic** [comment]
I now see that I tagged the release on github, but didn't actually push it
to crates.io, sorry about that. I'm afraid the formal release will have to
wait until Sunday when I get back home. As a workaround until then, you
should be able to specify the github repo and the `0.1.13` release tag
directly in your `Cargo.toml`.

**Comment by zonyitoo** [comment]
Okay. thanks!

**Comment by hniksic** [comment]
0.1.13 is now available on crates.io.

**Comment by zonyitoo** [comment]
Thanks a lot.
