### ISSUE TITLE
Support environment variables

### ISSUE THREAD

**Issue by tshepang** [hniksic/rust-subprocess#2]
Is this planned? Or maybe it's in the lib and I missed it?

**Comment by hniksic** [comment]
Yes, support for environment variables is planned, as well as for setting the current directory.

For the workaround is to temporarily set the environment variable before spawning the child. Note, though, that the temporary change will be seen by other threads.

**Comment by hniksic** [comment]
Environment variables are supported as of release 0.10.0.

**Comment by tshepang** [comment]
so nice, thanks
