### ISSUE TITLE
Incorrect winapi features?

### ISSUE THREAD

**Issue by danreeves** [hniksic/rust-subprocess#20]
In order to get this project compiling on windows I had to explicitly set winapi as my dependency and add "winerror" to the list of features. Otherwise you get the error:

```
error[E0432]: unresolved import `winapi::shared::winerror`
  --> C:\Users\travis\.cargo\registry\src\github.com-1ecc6299db9ec823\subprocess-0.1.16\src\win32.rs:22:25
   |
22 | pub use winapi::shared::winerror::{ERROR_BAD_PATHNAME, ERROR_ACCESS_DENIED};
   |                         ^^^^^^^^ Could not find `winerror` in `shared`
```

The correct config for me was:
```
[target.'cfg(windows)'.dependencies]
winapi = { version = "0.3.6", features = ["handleapi", "namedpipeapi", "processenv", "synchapi", "winerror"] }
```

Is this expected?

**Comment by hniksic** [comment]
It's not expected, and compilation works for me on my test (virtual) machine running Windows 10.

What version of rustc/cargo are you using?

**Comment by danreeves** [comment]
Hi, this was running in Travis CI new Windows support, which runs [Windows Server 2016](https://docs.travis-ci.com/user/reference/windows/#windows-version). If it's helpful you can see the build that failed [here](https://travis-ci.org/danreeves/cargo-cmd/jobs/440479706)

```
$ rustc --version
rustc 1.31.0-nightly (77af31408 2018-10-11)
$ rustup --version
rustup 1.14.0 (a364ad985 2018-09-25)
$ cargo --version
cargo 1.31.0-nightly (ad6e5c003 2018-09-28)
```

```
subprocess = "0.1.16"
```

**Comment by hniksic** [comment]
I cannot reproduce this even after switching to nightly. But the changes you propose sound like they shouldn't cause problems, so I can merge them anyway, if you're willing to submit a PR.

I didn't know Travis CI offered Windows integration; I'll look into it.
