### ISSUE TITLE
Cannot check for exit code/status when stream_stdout() is used

### ISSUE THREAD

**Issue by nbigaouette** [hniksic/rust-subprocess#26]
When using `stream_stdout()`, the [`Exec` is consumed](https://docs.rs/subprocess/0.1.18/subprocess/struct.Exec.html#method.stream_stdout) and thus it becomes impossible to check the process' status (or error) code.

Because of this it's not possible to detect any problem with subprocesses; I had the false impression that my subprocess was running successfully.

I'd like to read the process' stderr & stdout but still verify its return code. Is that possible?

**Comment by nbigaouette** [comment]
I've managed to do what I wanted (read stdout/stderr line by line and checking the exit code).

I had to move away from `stream_stdout()`.

First, I used [`Exec::popen()`](https://docs.rs/subprocess/0.1.18/subprocess/struct.Exec.html#method.popen) method: https://github.com/nbigaouette/pycors/blob/1ad94ab9fda1c05c8792c890f6a59e1f3f35666d/src/utils.rs#L330-L335

I then `std::mem::swap()` the `Popen`'s `stdout` with a `None`: https://github.com/nbigaouette/pycors/blob/1ad94ab9fda1c05c8792c890f6a59e1f3f35666d/src/utils.rs#L337-L339

I can now read from the `stdout` line by line: https://github.com/nbigaouette/pycors/blob/1ad94ab9fda1c05c8792c890f6a59e1f3f35666d/src/utils.rs#L341

I can finally wait for the process to finish and get its exit status: https://github.com/nbigaouette/pycors/blob/1ad94ab9fda1c05c8792c890f6a59e1f3f35666d/src/utils.rs#L374-L376

and match any error: https://github.com/nbigaouette/pycors/blob/1ad94ab9fda1c05c8792c890f6a59e1f3f35666d/src/utils.rs#L387-L415

**Comment by hniksic** [comment]
The approach you settled on is correct. `stream_stdout` is a convenience method that has the downside of consuming `Exec`.

**Comment by hniksic** [comment]
@nbigaouette Also, now that you can [`take`](https://doc.rust-lang.org/std/option/enum.Option.html#method.take) stdout from the `Popen` struct, which does the same thing as swapping it with `None`, but looks nicer to a human reader.
