### ISSUE TITLE
How to get stdout, stderr, exit_code and timeout

### ISSUE THREAD

**Issue by gregberns** [hniksic/rust-subprocess#29]
Hey, first thanks for a great project, its exactly what I needed.

So I'm looking to execute processes which have no stdin, but I need to capture:
* stdout
* stderr
* exit_code 
* and time out a process

I've tried a whole bunch of things. The closest I've gotten is to use the `Popen` and use the `communicate_bytes` to get the first 3 of the bullets above, but it blocks and so the `wait_timeout` doesn't get called.

I looked through other issues, but may have missed it. Any ideas on how to accomplish this?

```rs
//This should timeout after 50ms, but blocks on `communicate_bytes` so the `wait_timeout` never can check
#[test]
fn test_sleep_with_timeout_blocks() {
    
    let timeout = Duration::from_millis(50);
    let args = &vec!("sh", "-c", "sleep 5");

    let mut p = Popen::create(
        args, 
        PopenConfig {
            stdout: Redirection::Pipe,
            stderr: Redirection::Pipe,
            ..Default::default()
        }).unwrap();

    // This blocks, so the wait_timeout cant get hit
    // I need the stdout and stderr
    let (maybe_out, maybe_err) = p.communicate_bytes(None).unwrap();
    
    let status = p.wait_timeout(timeout).unwrap();
}
```

**Comment by hniksic** [comment]
I think the easiest way to accomplish that is to spawn threads that read from `stdout` and `stderr` (which you can move out of `Popen` and into to the threads). In the main thread you can use `wait_timeout()` and kill the process if it times out, thereby automatically unblocking the threads. (This is how `communicate()` is implemented on Windows.)

Basically, `communicate()` is a convenience function that handles simultaneous writes/reads to the three relevant streams. It doesn't support a timeout for technical reasons - on Windows, a timeout that doesn't involve killing the process would leave the helper threads stuck. But your timeout logic can explicitly kill the process, thus allowing the threads to exit.

**Comment by gregberns** [comment]
@hniksic Thanks for the suggestion. I think I understand what you're saying, but I'm struggling to implement. I've added a `spawn` and `move`, but when I try and access `p.stdout` (Option<File>) and read the file, the compiler/borrow checker doesn't like it. I've tried a ton of different things, but cant get it to compile.

Is there a different way I can get access to the `stdout`? Should I be referring to the `stdout` on the `Popen` struct and passing it to the thread? Or is there another approach I can try?

I also tried to `let thread_stdout = &p.stdout` before the thread, but had lots of borrow checker issues.

Thanks for the help so far, its very appreciated.

Right now I'm just focused on a unix implementation, just fyi.

```
#[test]
fn test_sleep_with_timeout_fails() {
    
    let timeout = Duration::from_millis(5);
    let args = &vec!("sh", "-c", "sleep 5");

    let mut p = Popen::create(
        args, 
        PopenConfig {
            stdout: Redirection::Pipe,
            stderr: Redirection::Pipe,
            ..Default::default()
        }).unwrap();

    let handle: JoinHandle<(Vec<u8>, Vec<u8>)> = thread::spawn(move || {
        // Can't figure out how to access `p.stdout` here
        let out = p.stdout.as_ref().map(|mut f| {
            let mut buffer = Vec::new();
            //And there are issues reading from mut file from immutible ref
            f.read_to_end(&mut buffer).unwrap();
            buffer
        }).unwrap_or_else(|| Vec::new());
        //stderr excluded...
        (out, Vec::new())
    });

    let status = p.wait_timeout(timeout).unwrap();

    let (out, err) = handle.join().unwrap();

    //Other details here...
    //if status == None
    // p.kill()?;
    // p.wait()?;
}
```

```
error[E0382]: borrow of moved value: `p`
   --> src/processor.rs:340:18
    |
320 |     let mut p = Popen::create(
    |         ----- move occurs because `p` has type `subprocess::popen::Popen`, which does not implement the `Copy` trait
...
328 |     let handle: JoinHandle<(Vec<u8>, Vec<u8>)> = thread::spawn(move || {
    |                                                                ------- value moved into closure here
329 |         // Can't figure out how to access `p.stdout` here
330 |         let out = p.stdout.as_ref().map(|mut f| {
    |                   - variable moved due to use in closure
...
340 |     let status = p.wait_timeout(timeout).unwrap();
    |                  ^ value borrowed here after move
```

**Comment by hniksic** [comment]
You need to *take* the `stdout` and `stderr` from `p` and then `move` each into its respective closure. I don't have time to test it right now, but it should be something like:

```rust
let (mut stdout, mut stderr) = (p.stdout.take().unwrap(), p.stderr.take().unwrap());
let out_handle: JoinHandle<io::Result<Vec<u8>>> = thread::spawn(move || {
    let mut buffer = Vec::new();
    stdout.read_to_end(&mut buffer)?
    buffer
});
let err_handle: // ... same thing for stderr
// both threads are now running _in parallel_
let status = p.wait_timeout(timeout).unwrap();
let out = out_handle.join().unwrap();
let err = err_handle.join().unwrap();
```

**Comment by gregberns** [comment]
Works!! Thank you!!! I've got to refine and test it more. I'll update with the working code.

**Comment by gregberns** [comment]
Here's a working test that runs `echo hello && sleep 1`, times out, and gets the stdout/stderr.

Again, thank you, this was one of the last critical changes I needed for porting my project to Rust ([fcheck](https://github.com/gregberns/fcheck)).

```
#[test]
fn test_sleep_with_timeout_fails() {
    
    let timeout = Duration::from_millis(100);
    let args = &vec!("sh", "-c", "echo hello && sleep 1");

    let mut p = Popen::create(
        args, 
        PopenConfig {
            stdout: Redirection::Pipe,
            stderr: Redirection::Pipe,
            ..Default::default()
        }).unwrap();

    let (mut stdout, mut stderr) = (p.stdout.take().unwrap(), p.stderr.take().unwrap());
    let out_handle: JoinHandle<IoResult<Vec<u8>>> = thread::spawn(move || {
        let mut buffer = Vec::new();
        stdout.read_to_end(&mut buffer)?;
        Ok(buffer)
    });
    let err_handle: JoinHandle<IoResult<Vec<u8>>> = thread::spawn(move || {
        let mut buffer = Vec::new();
        stderr.read_to_end(&mut buffer)?;
        Ok(buffer)
    });
    // both threads are now running _in parallel_
    let status = p.wait_timeout(timeout).unwrap();
    let out = out_handle.join().unwrap();
    let err = err_handle.join().unwrap();

    assert!(status.is_none());

    if status.is_none() {
        p.kill().unwrap();
        p.wait().unwrap();
    }

    assert_eq!("hello\n", String::from_utf8(out.unwrap()).unwrap());
}
```

**Comment by hniksic** [comment]
@gregberns As of version 0.2.0, there is a version of `communicate` that accepts timeout (as well as allocation limit on captured output), so you no longer have to use threads.
