### ISSUE TITLE
Timeout in communicate

### ISSUE THREAD

**Issue by palaviv** [hniksic/rust-subprocess#30]
Hi,
I am implementing subprocess in [RustPython](https://github.com/RustPython/RustPython) and this project fits perfectly :smirk:.
I would like to allow timeout in `communicate` which is currently not supported. Do you have any plan of supporting it in the future? Would you accept a PR that adds timeout?
In case you would like to add timeout would you prefer adding a optional timeout parameter to `communicate` and `communicate_bytes` or adding functions named `communicate_timeout` and `communicate_bytes_timeout`?

**Comment by hniksic** [comment]
Sorry about taking long to respond.

An optional timeout parameter would be a backward-incompatible change which I'd prefer not to make (for that sole purpose), so the second option sounds nicer.

I'm curious, how do you plan to make the timeout work on Windows?

**Comment by hniksic** [comment]
Perhaps timeout on Windows would be possible using [`GetCommTimeouts`](https://docs.microsoft.com/en-us/windows/win32/api/winbase/nf-winbase-getcommtimeouts) and [`SetCommTimeouts`](https://docs.microsoft.com/en-us/windows/win32/api/winbase/nf-winbase-setcommtimeouts)?

**Comment by hniksic** [comment]
The latest `subprocess` adds a new method `start_communicate()` which returns a handle that supports:

* timeouts
* size limit on captured data
* repeated invocations on the same subprocess (e.g. after a timeout or a size limit)
* obtaining the output captured so far in case of any error
