### ISSUE TITLE
Example improvement and Exec::cmd problem on Windows

### ISSUE THREAD

**Issue by swaldhoer** [hniksic/rust-subprocess#36]
First an idea to improve the example which might relevant for users of this crate that take the
example from [examples/sample.rs](https://github.com/hniksic/rust-subprocess/blob/fa60ef18244d8edcc1b3146f100e595e264cdd9b/examples/sample.rs).
Shell builtin commands on Windows, like e.g., ``dir``, need to always be run through ``subprocess::Exec::shell``. I used the following code to get the example working on Windows (if you like I'll be happy to open a Pull Request):

```rust
extern crate subprocess;

use std::io::{BufRead, BufReader};
use subprocess::Exec;

fn main() {
    #[cfg(not(target_family = "windows"))]
    let x = Exec::cmd("ls").stream_stdout().unwrap();
    #[cfg(target_family = "windows")]
    // on Windows shell builtins like dir need to be run through shell not cmd
    let x = Exec::shell("dir").stream_stdout().unwrap();

    let br = BufReader::new(x);
    for (i, line) in br.lines().enumerate() {
        println!("{}: {}", i, line.unwrap());
    }
}
```

Furthermore I think there is bug on Windows. Passing a command that is built on more then one word (meaning something surrounded by whitespace), does not work if it passed to
``subprocess::Exec::cmd``. Simple example:

```rust
fn main() {
    let x = Exec::shell("cargo").stream_stdout().unwrap();              // works
    let x = Exec::cmd("cargo").stream_stdout().unwrap();                // works
    let x = Exec::shell("cargo --version").stream_stdout().unwrap();    // works
    let x = Exec::cmd("cargo --version").stream_stdout().unwrap();      // does NOT work

    let br = BufReader::new(x);
    for (i, line) in br.lines().enumerate() {
        println!("{}: {}", i, line.unwrap());
    }
}
```

The error message for the non working example is:

```rconsole
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: IoError(Os { code: 2, kind: NotFound, message: "..." })', src\main.rs:7:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

For the reasons mentioned in the [README.md](https://github.com/hniksic/rust-subprocess/blob/fa60ef18244d8edcc1b3146f100e595e264cdd9b/README.md#spawning-and-redirecting) I think it would be good if ``subprocess::Exec::cmd`` works well with that type of input on Windows.

**Comment by hniksic** [comment]
> Shell builtin commands on Windows, like e.g., dir, need to always be run through `subprocess::Exec::shell`

The same is true on Unix, though - if the example were to use a shell built-in, e.g. `alias` or `cd`, it would also have to be run through shell. It is sort of tacitly assumed that the user of a crate like `subprocess` already knows such things, but now that you mention it, perhaps an explanatory comment in the example would be appropriate. I think using `#[cfg(...)]` to make the example "work" on Windows would go a tad too far because it would break its simplicity. The idea of the example is to just invoke the simplest possible command that does something, `ls` being such command on Unix. I wish there were a command that you could rely having on both Windows and Unix, but I'm not aware of one.

> Furthermore I think there is bug on Windows. Passing a command that is built on more then one word (meaning something surrounded by whitespace), does not work if it passed to

That's actually a feature. By using `shell` you opt into splitting by whitespace, as well as whatever other processing your shell implements, such as `$` expansion etc. But by using `cmd` you explicitly request to start that command and none other. If you had a `cargo --version.exe` on your `PATH`, `subprocess` would happily invoke it.

If you think the documentation of `cmd` could be improved to make this point stronger, I would support a PR in that direction.

**Comment by swaldhoer** [comment]
> > Shell builtin commands on Windows, like e.g., dir, need to always be run through `subprocess::Exec::shell`
>
> The same is true on Unix, though - if the example were to use a shell built-in, e.g. `alias` or `cd`, it would also have to be run through shell. It is sort of tacitly assumed that the user of a crate like `subprocess` already knows such things, but now that you mention it, perhaps an explanatory comment in the example would be appropriate. I think using `#[cfg(...)]` to make the example "work" on Windows would go a tad too far because it would break its simplicity. The idea of the example is to just invoke the simplest possible command that does something, `ls` being such command on Unix. I wish there were a command that you could rely having on both Windows and Unix, but I'm not aware of one.

Yep, thats my bad, ``ls`` is in contrast to ``dir`` not a shell builtin, sorry for that one.

``tar`` is a command that one could rely on [Windows](https://docs.microsoft.com/en-us/virtualization/community/team-blog/2017/20171219-tar-and-curl-come-to-windows) and the [Unix](https://pubs.opengroup.org/onlinepubs/007908799/xcu/tar.html), but the output is not that fancy as ``ls``/``dir`` ;).

> > Furthermore I think there is bug on Windows. Passing a command that is built on more then one word (meaning something surrounded by whitespace), does not work if it passed to
>
> That's actually a feature. By using `shell` you opt into splitting by whitespace, as well as whatever other processing your shell implements, such as `$` expansion etc. But by using `cmd` you explicitly request to start that command and none other. If you had a `cargo --version.exe` on your `PATH`, `subprocess` would happily invoke it.
>
> If you think the documentation of `cmd` could be improved to make this point stronger, I would support a PR in that direction.

Ok, maybe I have misinterpreted that *inspired by Python's subprocess module*, as this allows you (and encourages) to not run commands through the shell and works well with something like ``python --version`` or ``["python", "--version"]``. I will have a look and think about that documentation update.

But anyway don't you think, that passing a command like ``cargo --version`` should work fine when using something similar to `cmd` and not `shell`?
Maybe an extra method like `subprocess::Exec::cmd_from_list()` that can handle iterables and does not force you to use shell would a solution?

**Comment by hniksic** [comment]
> Ok, maybe I have misinterpreted that *inspired by Python's subprocess module*[...] But anyway don't you think, that passing a command like `cargo --version` should work fine when using something similar to `cmd` and not `shell`?

I think this is a misunderstanding on what `cmd` does, so let me try to elaborate. "Inspired by Python's subprocess module" just means that the `subprocess` crate is intended to have a similar feature set and a similar logic behind it as . In this case, the following three are equivalent:

```
# Python
subprocess.Popen(["cargo --version"])

// Rust, basic (Python-style) API
subprocess::Popen::create(&["cargo --version"], PopenConfig::default())?;

// Rust, builder API
Exec::cmd("cargo --version").join()?;
```

Each of them instructs the system to run the executable named `cargo --version` without arguments, and each of them fails in exactly the same way - with a "no such file or directory" system error, at least assuming you don't have a `cargo --version` executable lying around in your path. To start `cargo` command with the `--version` argument, you have many different options:

```
# Python, without shell
subprocess.Popen(["cargo", "--version"])
# Python, with shell
subprocess.Popen("cargo --version", shell=True)

// Rust, without shell
Popen::create(&["cargo", "--version"], PopenConfig::default())?;
Exec::cmd("cargo").arg("--version").join()?;

// Rust, with shell
Popen::create(&["sh", "-c", "cargo --version"], PopenConfig::default())?;  // Unix-specific
Popen::create(&["cmd.exe", "/c", "cargo --version"], PopenConfig::default())?;  // Windows-specific
Exec::shell("cargo --version").join()?;  // portable
```

Now let's assume `Exec::cmd("cargo --version")` just worked, i.e. that it split the string by whitespace and interpreted it as `Exec::cmd("cargo").arg("--version")` is interpreted now. Consider the following:

* What if you actually had a command called `cargo --version.exe` and wanted to execute it? It may look like a contrived example, but command (and especially directory) names do contain whitespace, and splitting by whitespace would seriously compromise the ability to run an arbitrary command.
* What if you wanted to run `cargo "some argument that contains spaces"`? Would `Exec::cmd` then also need to parse double quotes? What if you wanted to pass an argument that contained quotes? `Exec::cmd` would then need to also support a mechanism for *escaping* quotes. Which quoting and escaping mechanism would you implement? Keep in mind that such things differ not only from OS to OS but from shell to shell.
* Once you parse spaces, double quotes and backslashes, what about variable substitution - things like `cargo --user $USERNAME`? Would you expect `Exec::cmd` to support those, as well as means to escape the `$` sign when you actually need it?
* What about other shell-like constructs, such as `Exec::cmd("ls | grep foo")` or `Exec::cmd("grep `cat file1` file2")`?

The point I'm trying to make is that `Exec::cmd` is designed to do one thing and do it well, and that is: start the command specified by the string, without any arguments. Parsing command lines is a complicated matter, and often prone to security and injection risks, especially when confronted with untrusted input. The subprocess crate side-steps the issue by offering a simple way of letting the shell do the work and the secure (and precise) way of letting subprocess know what it is you want.

**Comment by hniksic** [comment]
> Maybe an extra method like `subprocess::Exec::cmd_from_list()` that can handle iterables and does not force you to use shell would a solution?

Note that there is already `args()`, so you can use `Exec::cmd(command).args(arglist)`. (`args` doesn't accept an iterable, but it probably should.)

**Comment by swaldhoer** [comment]
Thanks for that extensive answer, it explained things very well.
I now think that what ``Exec::cmd`` does is perfectly fine. I still need the time to read the docs fully to think about, if the documentation needs to be extended there.

> Note that there is already ``args()``, so you can use ``Exec::cmd(command).args(arglist)``. (args doesn't accept an iterable, but it probably should.)

Yes this solves my point about ``Exec::cmd_from_list()``. Yes if it would accept iterables that would be perfect.

Thanks for your answers, and if you think, that the documentation does not need to be extended, feel free to close this issue.

**Comment by hniksic** [comment]
> Thanks for your answers, and if you think, that the documentation does not need to be extended, feel free to close this issue.

I will close this issue, but I'd consider a PR that improves `cmd` docs to make it clearer why things like `cmd("cargo --version")` can't work, e.g. that it specifies the _name_ of the command, not the full command line.
