### ISSUE TITLE
Unix shell defaults to sh rather than bash

### ISSUE THREAD

**Issue by gilescope** [hniksic/rust-subprocess#37]
Unix shell defaults to sh rather than bash. I would suggest that the default shell for executing some shell stuff these days is bash. If the default is bash then more stuff will just work first time.

I think it's at least worth considering switching the default or making it an option...

**Comment by hniksic** [comment]
`/bin/sh` is the default system shell on Unix-like systems, which is guaranteed to be present at that exact location and is often faster and more secure than the alternatives. (Ubuntu uses `dash` as its `/bin/sh` to reduce bloat and increase security.)

`subprocess` uses the shell just to execute a command line provided as a string, such as `cargo --version` or `find | sort`. Command lines passed to `Exec::shell()` should not contain advanced shell scripting constructs where the difference between `bash` and `dash` could be observed. Users who want to pass bash-specific constructs to `subprocess` should use `Exec::cmd("bash").arg("-c").arg(<code>)`, which is guaranteed to run `bash`.

The Python [subprocess module](https://docs.python.org/3/library/subprocess.html#subprocess.Popen), which this module is based on, as well as the libc functions such as [`system`](http://man7.org/linux/man-pages/man3/system.3.html) and [`popen`](http://man7.org/linux/man-pages/man3/popen.3.html) C function, all use `/bin/sh -c` to execute the provided command line.

> I think it's at least worth considering switching the default or making it an option...

I would consider a configuration option, but it has a scoping issue. If it configured the default for the whole process, configuring a non-standard shell might break other unrelated uses of `subprocess` by other crates. And if it configured the shell per-`Exec`, then it seems no more convenient than just using `Exec::cmd("bash").arg("-c")`. What configuration strategy did you have in mind?

**Comment by gilescope** [comment]
Yep will just call out to bash. I guess I was thinking a feature flag, but as you say it’s not much trouble to call bash directly (you just have to remember the gotcha that all arguments are passed in the first argument).

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by hniksic** [comment]
> but as you say it’s not much trouble to call bash directly (you just have to remember the gotcha that all arguments are passed in the first argument).

Also note that the same gotcha would apply if `subprocess` called `bash` for you - it would still use the `-c` flag because the alternative would be to write the command line to a temporary file, which is inefficient and error-prone.
