### ISSUE TITLE
Debug output does not display status of environment flags

### ISSUE THREAD

**Issue by alerque** [hniksic/rust-subprocess#39]
Given the code:

```rust
let process = Exec::Cmd("mycommand").env("MYVAR", "true").arg("myarg");
eprintln!("Incantation = {:#?}", process);
```

I would expect to see some information about the environment variable that will be set when that process is run. Instead I only see information about the command and the argument, nothing is mentioned about the environment variable.

**Comment by hniksic** [comment]
Do you have a suggestion how to format the output to make this information apparent?

So far the `Debug` output has been provided on a best-effort basis, without presuming to include the whole information about the object.

**Comment by alerque** [comment]
Since you are currently outputting a pseudo shell command string, the most obvious addon would be just to prefix the vars in a POSIX format like: `MYVAR=true mycommand myarg`.

Personally my preference would be to replace the whole lossy string thing (since it is very likely not to be an exact equivalent of what is run and therefore likely to misslead and just use the `#[derive(debug)]` implementations for the various enums and structs used to assemble the final thing. Perhaps that could be the Debug trait and the current string format thing could be the Display trait.

**Comment by hniksic** [comment]
The current behavior was introduced in #10, but might have been a mistake. Before reverting to `derive(Debug)`, I think it would make sense to take a look at what builder types in well-respected crates are doing.

**Comment by hniksic** [comment]
Implemented in the next release.
