### ISSUE TITLE
I'm having issue importing subprocess

### ISSUE THREAD

**Issue by NullVoxPopuli** [hniksic/rust-subprocess#4]
```rust
extern crate subprocess;

use subprocess::*;

pub fn run(script: &str) -> String {
    let result = { Exec::shell(script) }
        .capture()?
        .stdout_str();

    result.to_string()
}
```

![2017-04-18-092543_622x175_scrot](https://cloud.githubusercontent.com/assets/199018/25132886/06fbcf44-2419-11e7-8646-14f79d0f2a1d.png)

what am I doing wrong?

I'm new to rust, as well. Using Rust 1.16

**Comment by hniksic** [comment]
This is not an issue with subprocess itself, but with how Rust resolves `extern crate` declarations. See, for example, [this issue](https://github.com/rust-lang/rust/issues/17056).

The correct solution is to move the `extern crate subprocess` declaration to `main.rs` or `lib.rs`, whichever applies to your crate.

**Comment by NullVoxPopuli** [comment]
thanks! 

I moved `extern crate subprocess` from `shell.rs` to `main.rs`, and that issue went away. thanks!
