### ISSUE TITLE
Cannot compile from latest master

### ISSUE THREAD

**Issue by rgeorgiev583** [hniksic/rust-subprocess#41]
- `rustup` toolchain: `stable-x86_64-unknown-linux-gnu`
- `rustc` version: `1.39.0`

I noticed the issue for the first time while I was trying to update the Cargo crates on my system via `cargo install-update -a` (which tried to install `subprocess v0.2.4`).  After that, I tried to clone the repository and run `cargo build` in it, and it failed with the same error:
```
   Compiling subprocess v0.2.5
error[E0658]: the `#[non_exhaustive]` attribute is an experimental feature
    --> src/popen.rs:1251:1
     |
1251 | #[non_exhaustive]
     | ^^^^^^^^^^^^^^^^^
     |
     = note: for more information, see https://github.com/rust-lang/rust/issues/44109

error: aborting due to previous error

For more information about this error, try `rustc --explain E0658`.
error: could not compile `subprocess`.
```

I think that switching to a `nightly` toolchain would resolve my issue.  However, I suppose that would force me to use said toolchain when building dependent crates/projects as well.  What is more, I'm not aware of such a requirement being mentioned in the documentation (but please correct me if I'm wrong).

**Comment by hniksic** [comment]
The `non_exhaustive` attribute was stabilized in [Rust 1.40.0](https://blog.rust-lang.org/2019/12/19/Rust-1.40.0.html), so you need to use that (or newer) to compile the latest `subprocess`.

**Comment by rgeorgiev583** [comment]
@hniksic, thanks for the suggestion; I updated to 1.43.1 and that resolved the issue!
