### ISSUE TITLE
Can't get example reading output to work with timeout

### ISSUE THREAD

**Issue by zaddach** [hniksic/rust-subprocess#43]
Hi,

I'm trying to write an example with the subprocess crate that reads output from a process, and terminates the process after a timeout if the process didn't terminate yet. I'm using another thread to terminate/kill the process after the timeout passed, and read its output in the main thread.

What I'd expect from the below code is the following output:
```
Starting to read output
Wait timed out, terminating process
Terminated process successfully
Everything fine
Output: Hi There!

Hello, world!
```
and the program terminates.
What it actually get is:
```
Starting to read output
Wait timed out, terminating process
Terminated process successfully
Everything fine
```
and the program doesn't terminate. Could you help me getting this example to work?

```rust
use subprocess::{Popen, PopenConfig, Redirection};
use std::io::Read;
use std::time::Duration;


fn main() {
    let mut p = Popen::create(&["bash", "-c", "echo \"Hi There!\"; sleep 1000"], PopenConfig {stdout: Redirection::Pipe, ..Default::default()}, ).unwrap();
    let mut output = p.stdout.take().unwrap();

    let thread = std::thread::spawn(move || {
        let three_secs = Duration::from_secs(3);
        let one_sec = Duration::from_secs(1);
        let r = p.wait_timeout(three_secs).unwrap();
        match r {
            None => {
                println!("Wait timed out, terminating process");
                p.terminate().unwrap();
                let r = p.wait_timeout(one_sec).unwrap();
                match r {
                    None => {
                        println!("Termination didn't seem to work, killing");
                        p.kill().unwrap();
                    },
                    Some(_) => {
                        println!("Terminated process successfully");
                    },
                }
                p.wait().unwrap();},
            Some(_) => { println!("Process returned");},
        }
        println!("Everything fine");
    });

    println!("Starting to read output");
    let mut output_str = String::new();
    output.read_to_string(&mut output_str).unwrap();
    println!("Done reading output");
    thread.join().unwrap();

    println!("Output: {}", output_str);
    println!("Hello, world!");
}
```

**Comment by hniksic** [comment]
The problem with your example is that Bash spawns another process, `sleep`. The call to `terminate()` terminates only Bash, but Bash's output got inherited by `sleep`. This is why reading `p.stdout` will block until the other side of the pipe is closed, i.e. until `sleep 1000` (and other processes that might have inherited it) terminate.

This is not unique to `subprocess`, I believe you'd have the same issue with other libraries that spawn subprocesses, on both Unix and Windows. If you can describe your actual use case in more detail, I might be able to suggest a solution.
