### ISSUE TITLE
docs are a little confusing about "deadlock-free"

### ISSUE THREAD

**Issue by davepacheco** [hniksic/rust-subprocess#45]
A bunch of the documentation around `Communicator` and the `communicate` functions talks about being "deadlock-free":

> Deadlock-free communication with the subprocess.

It might be worth mentioning that it's still possible to create deadlocks if the child and parent processes share a pipe and the child attempts to write more data than the pipe's buffer size and the parent doesn't read it until after the child exits (which is a common pattern, even if it's buggy).  Here's an example program that does this:

```rust
use std::time::Duration;
use subprocess::Exec;
use subprocess::NullFile;
use subprocess::Redirection;

const BYTES: usize = 65536;
const TIMEOUT: Duration = Duration::from_secs(10);

fn main() {
    let exec = Exec::cmd("dd")
        .arg("if=/dev/zero")
        .arg("of=/dev/stdout")
        .arg("bs=1")
        .arg(&format!("count={}", BYTES));

    eprintln!("will run: {}", exec.to_cmdline_lossy());

    let mut subproc = exec
        .stdin(NullFile)
        .stdout(Redirection::Pipe)
        .stderr(Redirection::Pipe)
        .detached()
        .popen()
        .expect("failed to start command");

    let exit_status = subproc
        .wait_timeout(TIMEOUT)
        .expect("failed to wait for command")
        .expect("timed out waiting for command");

    let (stdout_text, stderr_text) = match subproc
        .communicate(None)
        .expect("failed to communicate with command")
    {
        (Some(stdout), Some(stderr)) => (stdout, stderr),
        _ => panic!("missing stdout or stderr"),
    };

    println!(
        "{:?} stdout_bytes={} stderr_bytes={}",
        exit_status,
        stdout_text.len(),
        stderr_text.len(),
    )
}
```

This just forks `dd` to write `BYTES` bytes from /dev/zero to stdout and waits up to 10 seconds.  If you set `BYTES` to a number larger than your system's pipe buffer (65536 bytes on my MacOS system), this program will blow up after 10 seconds, having timed out.

Obviously this isn't a problem with `subprocess`, but when I saw the references to "deadlock-free", I thought this module was claiming to handle this case (and I wondered how it does that, does it use other threads, does it use arbitrary memory, etc.).

**Comment by hniksic** [comment]
"Deadlock-free communication" refers to the call to `communicate()`. Your code times out precisely because it _doesn't_ call `communicate()` to drain the buffer. If you change the example to call `communicate()` instead of `wait_timeout()`, the deadlock is avoided, as advertised.

I would consider it to be reasonably clear that for `communicate()` to be deadlock-free, you're supposed to actually call that function. But perhaps I'm missing something - can you please elaborate?

**Comment by hniksic** [comment]
The documentation for `communicate()` and `communicate_start()` is now more explicit about what is meant by "deadlock-free" (and throw around the term less often).

**Comment by davepacheco** [comment]
Sorry for my lack of response -- and thanks for improving it anyway!

**Comment by hniksic** [comment]
@davepacheco No problem, thanks for actually bringing the docs issue to my attention.
