### ISSUE TITLE
can't call multiple time communicate_start with input

### ISSUE THREAD

**Issue by marius851000** [hniksic/rust-subprocess#49]
Hello. I made a python program that use stdin and stdout to communicate with a rust program. However, when I want to run communicate_start for the second time (after some output from python), I get a panic from subprocess:
``thread 'main' panicked at 'cannot provide input to non-redirected stdin', /home/marius/.cargo/registry/src/github.com-1ecc6299db9ec823/subprocess-0.2.4/src/communicate.rs:549:9``

I suppose this is caused by calling multiple time the communicate_start function with input. Here is a programm that demonstrate that:
```
use std::io::Read;
use std::time::Duration;
use subprocess::{Exec, PopenConfig, Redirection};
fn main() {
    let mut p = Exec::cmd("python")
        .stdin(Redirection::Pipe)
        .stdout(Redirection::Pipe)
        .stderr(Redirection::Merge)
        .popen()
        .unwrap();

    let mut c = p.communicate_start(Some(b"print(1)".to_vec())).limit_time(Duration::from_millis(5));
    let _ = c.read();
    let _ = c.read();
    let _ = c.read();

    let mut c2 = p.communicate_start(Some(b"print(1)".to_vec())).limit_time(Duration::from_millis(5));
    let _ = c.read();
}
```

I see nothing in the doc about this not being able to be done. I am on a posix system (linux). 

here is the version string of rustc: ``1.48.0-nightly (d006f5734 2020-08-28)``

**Comment by hniksic** [comment]
The error you observe is a consequence of `communicate_start()` taking ownership of the subprocess's input and output streams. This makes it possible for it to e.g. close the input stream after writing the provided input, and thus signal to the subprocess that it is done writing. This might be more obvious if `communicate_start()` consumed the `Popen` value, but that would make it impossible to e.g. send a signal to the subprocess, or retrieve its exit status.

The deeper issue is that the `communicate` family of methods is not designed for interactive communication, it supports the simple case when you want to send some data to the subprocess, _close the input stream_, and read the subprocess's output _until closed_. The fact that closing the stream is used as terminator makes it fundamentally impossible to call `communicate` (or `communicate_start`) twice on the same subprocess. If you need interactive communication, you should write to `p.stdin` and read from `p.stdout` directly.

See [this comment](https://github.com/hniksic/rust-subprocess/issues/46#issuecomment-653742956) for additional detais.
