### ISSUE TITLE
Question: arecord | aplay

### ISSUE THREAD

**Issue by pvitaliy84** [hniksic/rust-subprocess#51]
Hello. I need help:

`{
   Exec::shell("/usr/bin/arecord -c 2 --format=cd --device=plughw:1,0") | Exec::shell("/usr.bin/aplay -c 2 --device=plughw:1,0")
 }.communicate().unwrap()`

It's work fine, but need next:
1) terminate (kill)
2) check working (if plug/unplug USB-audio card any time)

If you can, please give me example

**Comment by hniksic** [comment]
To terminate the process you can obtain the underlying `Popen` object:

```rust
let proc = (Exec... | Exec...).popen()?;
// to check whether it's working:
let still_working = self.poll.is_none();
// to terminate:
proc.terminate()?;
```

**Comment by pvitaliy84** [comment]
Thank you! You work is very cool!
