### ISSUE TITLE
can't modify subprocess process group id

### ISSUE THREAD

**Issue by 2000jedi** [hniksic/rust-subprocess#56]
I would like to change the subprocess' process group so that it would not terminate upon I call `SIGINT` on the main process.
I notice that in the current version, there is no such feature, and I have little control of the subprocess after it is forked().
Can you make an extra option to allow changing the subprocess to have an independent process group?

For example, set a boolean argument to be true when we call `process = process.setpgid()`.

Next, in the `fork()` function or `exec()` function, check the boolean argument. do something such as

    if process.setpgid {
        check_err(libc::setpgid(std::process::id() as i32, std::process::id() as i32))?;
    }

**Comment by hniksic** [comment]
I've now added the option to invoke `setpgid(0, 0)`, which I understand is equivalent to calling it with `getpid()`. Does that work for your use case?

**Comment by 2000jedi** [comment]
Yes, that would be great! Thank you!

**Comment by sourcefrog** [comment]
That's great, thank you! Could you please upload a new release including this change? It looks like 0.2.7 just missed it: https://docs.rs/subprocess/0.2.7/subprocess/struct.PopenConfig.html

**Comment by hniksic** [comment]
@sourcefrog Released now, thanks for the reminder.
