### ISSUE TITLE
Repeatedly writing and reading from stdio of a process

### ISSUE THREAD

**Issue by victoralan2** [hniksic/rust-subprocess#72]
I have been trying to do a simple task that involves opening [stockfish ](https://stockfishchess.org) (The chess engine), setting up a position (with the command `position fen {position string}`) and evaluating it (with the command `eval`). I want to do this efficiently for thousands of positions without having to close and open stockfish each single time. I wrote some code to do this but it seems to halt each time I try to read the stdout.
Here is my code:
```rust
pub fn create_stockfish() -> Popen { // Start the process
	let config = PopenConfig {
		stdout: Redirection::Pipe,
		stdin: Redirection::Pipe,
		stderr: Redirection::Pipe,
		..Default::default()
	};
	Popen::create(&[r"stockfish.exe"], config).unwrap()
}

pub fn generate(num_positions: usize) -> Vec<(Board, f32)> { 
	let mut generated = Vec::with_capacity(entries_per_core);
	let mut i = 0;
	let mut stockfish = create_stockfish();
	let mut stdin = stockfish.stdin.take().unwrap();
	let mut stdout = stockfish.stdout.take().unwrap();

	while i < num_positions {
		let random_board = random_board(&mut thread_rng());
		if let Ok(eval) = stockfish_eval(&random_board, &mut stdout, &mut stdin) { // Call stockfish
			generated.push((random_board, eval));
			i+=1;
		}
	}

	generated
}
pub fn stockfish_eval(position: &Board, stdout: &mut File, stdin: &mut File) -> anyhow::Result<f32> { // The actual part where I use this crate. Trying to comunicate with stockfish
	let position_fen = position.to_string();

	stdin.write_all(format!("position fen {}\neval\n", position_fen).as_bytes()).unwrap();
	let mut output = String::new();

	stdout.read_to_string(&mut output).unwrap(); // Halts here

	// Some nasty code to get the evaluation out of the output...

}
```

What am I doing wrong, and how can I fix the halt?

**Comment by hniksic** [comment]
`stdout.read_to_string()` attempts to read data until EOF. Since Stockfish continues running and waits for next input, it doesn't close stdout, and EOF never comes.

The fix is to stop reading when you detect that Stockfish has provided its full output. How that is done will depend on the format of the output. E.g. if it's supposed to come in one line, then you can try reading a line with something like this (untested):

```rust
use std::fs::File;
use std::io::Read;

fn read_line(source: &mut File) -> std::io::Result<String> {
    let mut line = vec![];
    let mut buf = [0u8; 4096];
    loop {
        let nread = source.read(&mut buf)?;
        if nread == 0 {
            break; // EOF
        }
        let data = &buf[..nread];
        if let Some(newline_pos) = data.iter().position(|&c| c == b'\n') {
            line.extend(&data[..newline_pos]);
            break;
        }
        line.extend(data);
    }
    Ok(String::from_utf8_lossy(&line).to_string())
}
```

**Comment by victoralan2** [comment]
Thank you! I modified your code to work with stockfish, and it worked perfectly!

Here is my modified code if anyone is interested:
```rust
fn read_until_end(source: &mut File) -> anyhow::Result<String> {
	let mut full_string = String::new();
	let mut buf = [0u8; 1024];
	loop {
		let nread = source.read(&mut buf)?;

		if nread == 0 {
			break; // EOF
		}
		let data = String::from_utf8(buf[..nread].to_vec())?;
		full_string.push_str(&data);
		if data.trim().ends_with("...]") {
			break;
		}
	}
	Ok(full_string)
}
```

**Comment by victoralan2** [comment]
Thank you! I modified your code to work with stockfish, and it worked perfectly!

Here is my modified code if anyone is interested:
```rust
fn read_until_end(source: &mut File) -> anyhow::Result<String> {
	let mut full_string = String::new();
	let mut buf = [0u8; 1024];
	loop {
		let nread = source.read(&mut buf)?;

		if nread == 0 {
			break; // EOF
		}
		let data = String::from_utf8(buf[..nread].to_vec())?;
		full_string.push_str(&data);
		if data.trim().ends_with("...]") {
			break;
		}
	}
	Ok(full_string)
}
```

**Comment by hniksic** [comment]
Looks great. Several stylistic points:

* you might want to call the function `read_until()`, and have it accept a `terminator: &str`. Then you can call it as `bla.read_until("...]")` (perhaps in another utility function, if you're calling it from multiple places), and it'll be reasonably clear to a future reader what's the code is doing.

* in theory a read might end in the middle of a UTF-8-encoded character, in which case you'll have a spurious error return from `from_utf8()`. This is why my code collected into a `Vec<u8>` and converted it to String at the end.

* it seems wasteful to allocate a `Vec` only to append it to `full_string`. You could get the same result without unnecessary allocation/copying by replacing `let data = String::from_utf8(buf[..nread].to_vec())?;` with `let data = std::str::from_utf8(&buf[..nread])?;`.
